<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * @copyright Copyright (c) 2025 Magebit, Ltd. (https://magebit.com/)
 * @author    Magebit <info@magebit.com>
 * @license   MIT
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="module" type="moduleType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueModuleName">
            <xs:selector xpath="module"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="moduleType">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="documentation" type="documentationType"/>
            <xs:element name="changelog" type="changelogType"/>
        </xs:choice>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="title" type="xs:string" use="optional"/>
        <xs:attribute name="sortOrder" type="xs:integer" use="optional"/>
        <xs:attribute name="icon" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="documentationType">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="path" type="xs:string" use="required"/>
        <xs:attribute name="acl" type="xs:string" use="optional"/>
        <xs:attribute name="sortOrder" type="xs:integer" use="optional"/>
    </xs:complexType>

    <xs:complexType name="changelogType">
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="path" type="xs:string" use="required"/>
        <xs:attribute name="acl" type="xs:string" use="optional"/>
        <xs:attribute name="sortOrder" type="xs:integer" use="optional"/>
    </xs:complexType>
</xs:schema>
